# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/f/MinecraftserverC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/f/MinecraftserverC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/f/MinecraftserverC/CMakeFiles /mnt/f/MinecraftserverC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/f/MinecraftserverC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

Externals/cJSON.o: Externals/cJSON.c.o
.PHONY : Externals/cJSON.o

# target to build an object file
Externals/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Externals/cJSON.c.o
.PHONY : Externals/cJSON.c.o

Externals/cJSON.i: Externals/cJSON.c.i
.PHONY : Externals/cJSON.i

# target to preprocess a source file
Externals/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Externals/cJSON.c.i
.PHONY : Externals/cJSON.c.i

Externals/cJSON.s: Externals/cJSON.c.s
.PHONY : Externals/cJSON.s

# target to generate assembly for a file
Externals/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Externals/cJSON.c.s
.PHONY : Externals/cJSON.c.s

extract_uuid.o: extract_uuid.c.o
.PHONY : extract_uuid.o

# target to build an object file
extract_uuid.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/extract_uuid.c.o
.PHONY : extract_uuid.c.o

extract_uuid.i: extract_uuid.c.i
.PHONY : extract_uuid.i

# target to preprocess a source file
extract_uuid.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/extract_uuid.c.i
.PHONY : extract_uuid.c.i

extract_uuid.s: extract_uuid.c.s
.PHONY : extract_uuid.s

# target to generate assembly for a file
extract_uuid.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/extract_uuid.c.s
.PHONY : extract_uuid.c.s

handshake.o: handshake.c.o
.PHONY : handshake.o

# target to build an object file
handshake.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/handshake.c.o
.PHONY : handshake.c.o

handshake.i: handshake.c.i
.PHONY : handshake.i

# target to preprocess a source file
handshake.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/handshake.c.i
.PHONY : handshake.c.i

handshake.s: handshake.c.s
.PHONY : handshake.s

# target to generate assembly for a file
handshake.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/handshake.c.s
.PHONY : handshake.c.s

login.o: login.c.o
.PHONY : login.o

# target to build an object file
login.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/login.c.o
.PHONY : login.c.o

login.i: login.c.i
.PHONY : login.i

# target to preprocess a source file
login.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/login.c.i
.PHONY : login.c.i

login.s: login.c.s
.PHONY : login.s

# target to generate assembly for a file
login.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/login.c.s
.PHONY : login.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.c.s
.PHONY : main.c.s

packet_utils.o: packet_utils.c.o
.PHONY : packet_utils.o

# target to build an object file
packet_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/packet_utils.c.o
.PHONY : packet_utils.c.o

packet_utils.i: packet_utils.c.i
.PHONY : packet_utils.i

# target to preprocess a source file
packet_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/packet_utils.c.i
.PHONY : packet_utils.c.i

packet_utils.s: packet_utils.c.s
.PHONY : packet_utils.s

# target to generate assembly for a file
packet_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/packet_utils.c.s
.PHONY : packet_utils.c.s

play.o: play.c.o
.PHONY : play.o

# target to build an object file
play.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/play.c.o
.PHONY : play.c.o

play.i: play.c.i
.PHONY : play.i

# target to preprocess a source file
play.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/play.c.i
.PHONY : play.c.i

play.s: play.c.s
.PHONY : play.s

# target to generate assembly for a file
play.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/play.c.s
.PHONY : play.c.s

server.o: server.c.o
.PHONY : server.o

# target to build an object file
server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.c.o
.PHONY : server.c.o

server.i: server.c.i
.PHONY : server.i

# target to preprocess a source file
server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.c.i
.PHONY : server.c.i

server.s: server.c.s
.PHONY : server.s

# target to generate assembly for a file
server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.c.s
.PHONY : server.c.s

socket_utils.o: socket_utils.c.o
.PHONY : socket_utils.o

# target to build an object file
socket_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/socket_utils.c.o
.PHONY : socket_utils.c.o

socket_utils.i: socket_utils.c.i
.PHONY : socket_utils.i

# target to preprocess a source file
socket_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/socket_utils.c.i
.PHONY : socket_utils.c.i

socket_utils.s: socket_utils.c.s
.PHONY : socket_utils.s

# target to generate assembly for a file
socket_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/socket_utils.c.s
.PHONY : socket_utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... Externals/cJSON.o"
	@echo "... Externals/cJSON.i"
	@echo "... Externals/cJSON.s"
	@echo "... extract_uuid.o"
	@echo "... extract_uuid.i"
	@echo "... extract_uuid.s"
	@echo "... handshake.o"
	@echo "... handshake.i"
	@echo "... handshake.s"
	@echo "... login.o"
	@echo "... login.i"
	@echo "... login.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... packet_utils.o"
	@echo "... packet_utils.i"
	@echo "... packet_utils.s"
	@echo "... play.o"
	@echo "... play.i"
	@echo "... play.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... socket_utils.o"
	@echo "... socket_utils.i"
	@echo "... socket_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

