#ifndef PACKET_IDS_H
#define PACKET_IDS_H

//=== Handshake packets ===

#define HANDSHAKE_SERVER_BOUND_PACKET 0x00
#define LEGACY_PING_PACKET 0xFE

//=== Status packets ===

#define STATUS_CLIENTBOUND_RESPONSE_PACKET 0x00
#define STATUS_CLIENTBOUND_PONG_PACKET 0x01
#define STATUS_SERVERBOUND_REQUEST_PACKET 0x00
#define STATUS_SERVERBOUND_PING_PACKET 0x01

//=== Login packets ===

#define LOGIN_CLIENTBOUND_DISCONNECT_PACKET 0x00
#define LOGIN_CLIENTBOUND_LOGIN_SUCCESS_PACKET 0x02
#define LOGIN_SERVERBOUND_LOGIN_START_PACKET 0x00

// === Play packets ===

// ==Clientbound play packets
//
#define PLAY_CLIENTBOUND_SPAWN_ENTITY_PACKET 0x00
#define PLAY_CLIENTBOUND_SPAWN_PLAYER_PACKET 0x05
#define PLAY_CLIENTBOUND_ENTITY_ANIMATION_PACKET 0x06
#define PLAY_CLIENTBOUND_CHAT_MESSAGE_PACKET 0x0F
#define PLAY_CLIENTBOUND_KEEP_ALIVE_PACKET 0x21
#define PLAY_CLIENTBOUND_CHUNK_DATA_PACKET 0x22
#define PLAY_CLIENTBOUND_JOIN_GAME_PACKET 0x26
#define PLAY_CLIENTBOUND_ENTITY_POSITION_PACKET 0x29
#define PLAY_CLIENTBOUND_ENTITY_POSITION_ROTATION_PACKET 0x2A
#define PLAY_CLIENTBOUND_ENTITY_ROTATION_PACKET 0x2B
#define PLAY_CLIENTBOUND_ENTITY_MOVEMENT_PACKET 0X2C
#define PLAY_CLIENTBOUND_PLAYER_INFO_PACKET 0x34
#define PLAY_CLIENTBOUND_PLAYER_POSITION_LOOK_PACKET 0x36
#define PLAY_CLIENTBOUND_DESTROY_ENTITIES 0x38

//== Serverbound play packets

#define PLAY_SERVERBOUND_CHAT_MESSAGE_PACKET 0x03
#define PLAY_SERVERBOUND_KEEP_ALIVE_PACKET 0x0F
#define PLAY_SERVERBOUND_PLAYER_POSITION_PACKET 0x11
#define PLAY_SERVERBOUND_PLAYER_POSITION_ROTATION_PACKET 0x12
#define PLAY_SERVERBOUND_PLAYER_ROTATION_PACKET 0x13
#define PLAY_SERVERBOUND_PLAYER_MOVEMENT_PACKET 0x14
#define PLAY_SERVERBOUND_ANIMATION_PACKET 0x2A




#endif // PACKET_IDS_H
